version: git-{branch}-{build}
image: Visual Studio 2017

environment:
  matrix:
  - EXTRA_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
    LAUNCH_BUILD: mingw32-make platform=win32
    LAUNCH_PATH: shell\linux\

build_script:
- cmd: >-
    set PATH=%EXTRA_PATH%;%PATH%
    
    cd %LAUNCH_PATH%
    
    %LAUNCH_BUILD%
  
after_build:
  - cmd: cd ..\..
  - cmd: mkdir artifacts
  - cmd: move shell\linux\nosym-reicast.exe artifacts/reicast-win_x64-fast-%APPVEYOR_REPO_COMMIT%.exe
  - cmd: copy %EXTRA_PATH%\libgcc_s_seh-1.dll artifacts
  - cmd: copy %EXTRA_PATH%\libwinpthread-1.dll artifacts
  - cmd: copy %EXTRA_PATH%\libgomp-1.dll artifacts

artifacts:
  - path: artifacts
    name: reicast-win_x64-fast-$(APPVEYOR_REPO_COMMIT)

deploy:
- provider: S3
  access_key_id: AKIAJETEBUZSLZF3YNKA
  secret_access_key:
    secure: ZxrysCeqMK99dOOzKyoeN4R5aO8JjA4RTrwVAQPQHz8sjyyKuVDZT2fC+9m6lUIi
  region: eu-west-1
  bucket: reicast-builds-windows
  folder: 'builds/heads/$(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_REPO_COMMIT)'
  artifact: reicast-win_x64-fast-$(APPVEYOR_REPO_COMMIT)
  set_public: true
